---
- name: install dependencies
  yum: name={{ item }} state=present
   name: "httpd,httpd-devel,apr,apr-devel,apr-util,apr-util-devel,gcc,gcc-c++,make,libtool,autoconf"
   state: present
- name: Ensure Apache is running
  service: name=httpd state=started enabled=yes
- name: Open port 80 for http access
  firewalld:
    service: http
    permanent: true
    state: enabled
- name: Restart the firewalld service to load in the firewall changes
  service: 
    name: firewalld 
    state: restarted