---
- name: Tomcat app server
  hosts: app
  become: yes
  tasks:
  - name: Ensure Java is installed.
    package:
      name: "java-1.8.0-openjdk"
      state: present

  - name: tomcat | group add
    group: name=tomcat

  - name: tomcat | user add
    user: name=tomcat group=tomcat home=/opt/tomcat8 createhome=no  

  - name: tomcat| test if binary already exists
    stat: 
      path: /tmp/apache-tomcat-8.5.40.tar.gz
    register: binarydl

  - name: tomcat | binary download
    get_url: 
      url: "http://mirror.nus.edu.sg/apache/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz"
      dest: "/tmp"
    when: binarydl.stat.exists == False

  - name: tomcat  | extract archive
    shell: "tar xzf /tmp/apache-tomcat-8.5.40.tar.gz -C /opt"

  - name: tomcat  | symlink install directory
    file: src="/opt/apache-tomcat-8.5.40" path="/opt/tomcat8" state=link
    
  - name: tomcat  | change ownership of target installation
    file: path="/opt/tomcat8" owner=tomcat group=tomcat state=directory recurse=yes

  - name : tomcat | run tomcat as a service
    template : src=tomcat.service.j2 dest=/etc/systemd/system/tomcat.service

  - name : tomcat | restart
    service :
      name: tomcat
      state: restarted

  - name : tomcat | copy local file to remote
    copy : 
       src: sample.war
       dest: /opt/tomcat8/webapps
       owner: tomcat
       group: tomcat
       mode: u=rwx,g=rx,o=r

  - name : Ensure application is deployed
    stat:
       path : /opt/tomcat8/webapps/sample

  - name : Check that you can connect before continue playbook
    uri:
       url: http://localhost:8080/sample/index.html
    register: result
    until: result.status == 200
    retries: 10
    delay : 10

  - name : Show result variable
    debug: 
      var: result
